language: rust
rust:
  - 1.30.0

jdk:
  - openjdk8

addons:
  apt:
    sources:
      - mono-nightly
    packages:
      - mono-devel

before_install:
  - pip install hererocks
  - hererocks lua53 -l5.3 -rlatest