services:
  - docker

before_install:
  - docker build -t rustacean -f Dockerfile.test .

env:
  - WEBHOOK_URL=https://discordapp.com/api/webhooks/524649101762232330/FgGVFuuUbyUt-5ZjmQUdjSS-SSaoId3PgtUURdjBq1nsP_DeiUrDgaqcvg8SGcKvkoqu

script:
  - docker run rustacean /bin/sh -c "cargo test"

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL