language: rust
rust: 
  - 1.33.0

before_install:
  - curl -sSL https://get.docker.com/ | sh
  - docker build -t kryod/rustacean-test -f Dockerfile.test .
  - cargo run build-images

script:
  - docker run -v /var/run/docker.sock:/var/run/docker.sock kryod/rustacean-test /bin/sh -c "cargo test"

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kryod/rustacean-test
  - docker build -t kryod/rustacean -f Dockerfile .
  - docker push kryod/rustacean
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL