language: rust
rust:
  - 1.30.0

services:
  - docker

before_install:
  - docker build -t rustacean -f Dockerfile.test .
  - docker ps -a
  - docker run rustacean /bin/sh -c "cargo test; bundle exec rake test"