[package]
name = "rustacean"
version = "0.1.0"
authors = ["Yohann Jerrain <y.jerrain@gmail.com>"]

[dependencies]
simplelog = "0.5.3"
log = "0.4.6"
rand = "0.6.1"
duct = "0.11.1"
regex = "1.1.0"
toml = "0.4.10"
serde = "1.0.83"
chrono = "0.4.6"
typemap = "0.3.3"
openssl-sys = "0.9.40"
serde_derive = "1.0.83"
diesel = { version = "1.3.3", features = [ "sqlite", "r2d2" ] }

[dependencies.serenity]
features = ["cache", "framework", "standard_framework"]
version = "0.5.11"
