[package]
name = "rustbot"
version = "0.1.0"
authors = ["Yohann Jerrain <y.jerrain@gmail.com>"]

[dependencies]
env_logger = "~0.4"
kankyo = "~0.1"
log = "~0.3"
rand = "0.5.5"

[dependencies.serenity]
features = ["cache", "framework", "standard_framework"]
version = "0.5"
